name: loan_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"   # Actualizado para Dart 3.8+

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^4.4.0
  intl: ^0.20.0
  provider: ^6.1.2
  google_fonts: ^6.1.0 
  shared_preferences: ^2.5.3
  currency_text_input_formatter: ^2.3.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.6.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  
  hive_generator: ^2.0.1
  build_runner: ^2.5.4   


flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#F5F5F5"   # o "#1E88E5" si quieres azul de fondo
  adaptive_icon_foreground: "assets/icons/app_icon.png"

